db.movies.insertMany([
  {
    rating: "8.8",
    Batch: "B42Wd",
    Gender: "Male",
    Name: "Raja",
    id: "2",
    yearsOfExperience: "3",
  },
  {
    id: "1",
    Name: "Narasimman",
    Batch: "B42Wd",
    Gender: "Male",
    yearsOfExperience: "2",
    rating: "8.5",
  },
  {
    id: "2",
    rating: "9.6",
    Name: "Raja",
    Batch: "B42Wd",
    Gender: "Male",
    yearsOfExperience: "3",
  },
  {
    id: "3",
    rating: "9.8",
    Name: "sanjay",
    Batch: "B42Wd",
    Gender: "Male",
    yearsOfExperience: "1",
  },
  {
    id: "4",
    rating: "8.10",
    Name: "sandya",
    Batch: "B42Wd",
    Gender: "Female",
    yearsOfExperience: "2",
  },
  {
    id: "5",
    rating: "8.9",
    Name: "saravanan",
    Batch: "B42Wd",
    Gender: "Male",
    yearsOfExperience: "4",
  },
]);
